name: Build and Release (Windows)

on:
  push:
    branches:
      - autoUpdate

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # 全タグ取得

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.0

      - name: Install dependencies
        run: npm ci

      - name: Get current and previous tag
        id: tags
        run: |
          $currentTag = "${GITHUB_REF##*/}"
          $prevTag = git tag --sort=-creatordate | Where-Object { $_ -ne $currentTag } | Select-Object -First 1
          echo "PREV_TAG=$prevTag" >> $env:GITHUB_ENV
          echo "CURRENT_TAG=$currentTag" >> $env:GITHUB_ENV

      - name: Get commits since previous tag
        id: commits
        run: |
          $commits = git log $env:PREV_TAG..HEAD --pretty=format:'- %s'
          echo "COMMITS=$commits" >> $env:GITHUB_ENV

      - name: Build & Publish (Windows)
        run: |
          npx electron-builder --win --x64 --publish always --config.extraMetadata.releaseNotes="$env:COMMITS"
        env:
          GH_TOKEN: ${{ secrets.github_token }}
          COMMITS: ${{ env.COMMITS }}
