name: Build and Release (Windows)

on:
  push:
    branches:
      - autoUpdate

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.0

      - name: Install dependencies
        run: npm ci

      - name: Build & Publish (Windows)
        run: npm run build -- --publish always
        env:
          GH_TOKEN: ${{ secrets.github_token }}