name: Build and Release (Windows)

on:
  push:
    tags:
      - 'v*'   # v1.0.0 のようなタグで起動

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.0

      - name: Install dependencies
        run: npm ci

      - name: Build & Publish (Windows)
        run: npm run build -- --publish always
        env:
          GH_TOKEN: ${{ secrets.github_token }}

      - name: Setup GitHub CLI
        uses: cli/gh-actions@v2

      - name: Authenticate GitHub CLI
        run: gh auth setup-git

      - name: List releases
        run: gh release list

      - name: Publish draft release # 最新の draft release を取得
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_DRAFT=$(gh release list --draft --limit 1 --json tagName --jq '.[0].tagName')
          echo "Latest draft release: $LATEST_DRAFT"
          if [ "$LATEST_DRAFT" != "null" ]; then
            gh release edit "$LATEST_DRAFT" --draft=false
            echo "Draft release '$LATEST_DRAFT' is now published as latest."
          else
            echo "No draft release found."
          fi